Я делала задание из прикрепленного файла с домашним заданием, и только при его загрузке увидела, что текстом написано вообще другое задание. 
Прошу дать еще времени для того, чтобы сделать и его.

## Тема «Создание признакового пространства»

In [1]:
# Импорт библиотек

import pandas as pd
import numpy as np

import warnings 
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [2]:
# Загрузка данных

df = pd.read_pickle('./tweets.pkl')
df.head(3)

,id,label,tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,0.0,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,...","[father, dysfunctional, selfish, drags, kids, ...","[father, dysfunct, selfish, drag, kid, dysfunc...","[father, dysfunctional, selfish, drag, kid, dy..."
1,2,0.0,thanks for lyft credit cannot use cause they d...,"[thanks, for, lyft, credit, can, not, use, cau...","[thanks, lyft, credit, use, cause, offer, whee...","[thank, lyft, credit, use, caus, offer, wheelc...","[thanks, lyft, credit, use, cause, offer, whee..."
2,3,0.0,bihday your majesty,"[bihday, your, majesty]","[bihday, majesty]","[bihday, majesti]","[bihday, majesty]"

1. Создайте мешок слов с помощью
sklearn.feature_extraction.text.CountVectorizer.fit_transform(). Применим его к 'tweet_stemmed'
и 'tweet_lemmatized' отдельно.

● Игнорируем слова, частота которых в документе строго превышает порог 0.9 с
помощью max_df.

● Ограничим количество слов, попадающий в мешок, с помощью max_features =
1000.

● Исключим стоп-слова с помощью stop_words='english'.

● Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с
помощью CountVectorizer.get_feature_names().

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
df['tweet_stemmed'] = df.tweet_stemmed.apply(lambda x: ' '.join(word for word in x))

In [5]:
# Создание мешка слов для 'tweet_stemmed' с помощью CountVectorizer

vectorizer_stemmed = CountVectorizer(stop_words='english', max_df=0.9, max_features=1000)
bag_of_words_stemmed = vectorizer_stemmed.fit_transform(df['tweet_stemmed'])

In [6]:
feature_names_stemmed = vectorizer_stemmed.get_feature_names()
pd.DataFrame(bag_of_words_stemmed.toarray(), columns = feature_names_stemmed)

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yo,yoga,york,young,youtub,yoyou,yoyour,yoyoy,yr,yummi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49154,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49155,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49156,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49157,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49158,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
df['tweet_lemmatized'] = df.tweet_lemmatized.apply(lambda x: ' '.join(word for word in x))

In [8]:
# Создание мешка слов для 'tweet_lemmatized' с помощью CountVectorizer

vectorizer_lemmatized = CountVectorizer(stop_words='english', max_df=0.9, max_features=1000)
bag_of_words_lemmatized = vectorizer_lemmatized.fit_transform(df['tweet_lemmatized'])

In [9]:
feature_names_lemmatized = vectorizer_lemmatized.get_feature_names()
pd.DataFrame(bag_of_words_lemmatized.toarray(), columns = feature_names_lemmatized)

,able,absolutely,account,act,action,actor,actually,adapt,add,adventure,...,yo,yoga,york,young,youtube,yoyou,yoyour,yoyoyou,yr,yummy
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49154,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49155,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49156,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49157,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49158,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

2. Создайте мешок слов с помощью sklearn.feature_extraction.text.TfidfVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.

● Игнорируем слова, частота которых в документе строго превышает порог 0.9 с
помощью max_df.

● Ограничим количество слов, попадающий в мешок, с помощью max_features =
1000.

● Исключим стоп-слова с помощью stop_words='english'.

● Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с
помощью TfidfVectorizer.get_feature_names().

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [11]:
# Создание мешка слов для 'tweet_stemmed' с помощью TfidfVectorizer

tfidf_vectorizer_stemmed = TfidfVectorizer(stop_words='english', max_df=0.9, max_features=1000)
values_stemmed = tfidf_vectorizer_stemmed.fit_transform(df['tweet_stemmed'])

In [12]:
feature_names_tfidf_stemmed = tfidf_vectorizer_stemmed.get_feature_names()
pd.DataFrame(values_stemmed.toarray(), columns = feature_names_tfidf_stemmed)

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yo,yoga,york,young,youtub,yoyou,yoyour,yoyoy,yr,yummi
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.744148,0.392399,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49154,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
49155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
49156,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
49157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
49158,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0

In [13]:
# Создание мешка слов для 'tweet_lemmatized' с помощью TfidfVectorizer

tfidf_vectorizer_lemmatized = TfidfVectorizer(stop_words='english', max_df=0.9, max_features=1000)
values_lemmatized = tfidf_vectorizer_lemmatized.fit_transform(df['tweet_lemmatized'])

In [14]:
feature_names_tfidf_lemmatized = tfidf_vectorizer_lemmatized.get_feature_names()
pd.DataFrame(values_lemmatized.toarray(), columns = feature_names_tfidf_lemmatized)

,able,absolutely,account,act,action,actor,actually,adapt,add,adventure,...,yo,yoga,york,young,youtube,yoyou,yoyour,yoyoyou,yr,yummy
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.742113,0.39173,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49154,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0
49155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0
49156,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0
49157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0
49158,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0

3. Проверьте ваши векторайзеры на корпусе который использовали на вебинаре, составьте
таблицу метод векторизации и скор который вы получили (в методах векторизации по
изменяйте параметры что бы добиться лучшего скора) обратите внимание как
падает/растёт скор при уменьшении количества фичей, и изменении параметров, так же
попробуйте применить к векторайзерам PCA для сокращения размерности посмотрите на
качество сделайте выводы

In [15]:
# Загрузка данных

data = open('corpus').read()
labels, texts = [], []
for i, line in enumerate(data.split("\n")):
    content = line.split()
    labels.append(content[0])
    texts.append(" ".join(content[1:]))


corpus_df = pd.DataFrame()
corpus_df['text'] = texts
corpus_df['label'] = labels
corpus_df.head(3)

                                                text       label
0  Stuning even for the non-gamer: This sound tra...  __label__2
1  The best soundtrack ever to anything.: I'm rea...  __label__2
2  Amazing!: This soundtrack is my favorite music...  __label__2

In [16]:
# Импорт библиотек

from sklearn import model_selection, preprocessing, linear_model
# from sklearn.metrics import accuracy_score
from sklearn.metrics import *

In [17]:
# Разобъем датасет на тренировочную и валидационную выборки

train_x, valid_x, train_y, valid_y = model_selection.train_test_split(corpus_df['text'], corpus_df['label'])

In [18]:
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
valid_y = encoder.fit_transform(valid_y)

In [19]:
# CountVectorizer

count_vectorizer = CountVectorizer(max_df=0.9) 
count_vectorizer.fit(corpus_df['text'])

xtrain_count =  count_vectorizer.transform(train_x)
xvalid_count =  count_vectorizer.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_count, train_y)
predictions = classifier.predict(xvalid_count)

acc_score = accuracy_score(valid_y, predictions)
acc_score

/Users/evgeniya/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8612

In [20]:
print(classification_report(predictions,valid_y))

              precision    recall  f1-score   support

           0       0.86      0.87      0.87      1304
           1       0.86      0.85      0.85      1196

    accuracy                           0.86      2500
   macro avg       0.86      0.86      0.86      2500
weighted avg       0.86      0.86      0.86      2500

In [21]:
# Таблица с результатами

results = pd.DataFrame() 

res1 = {'Type':'CountVectorizer', 'Score':acc_score}

results = results.append(res1, ignore_index=True)

In [22]:
# TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(max_df=0.9)
tfidf_vectorizer.fit(corpus_df['text'])

xtrain_tfidf =  tfidf_vectorizer.transform(train_x)
xvalid_tfidf =  tfidf_vectorizer.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_tfidf, train_y)
predictions = classifier.predict(xvalid_tfidf)

acc_score = accuracy_score(valid_y, predictions)
acc_score

0.8604

In [23]:
print(classification_report(predictions,valid_y))

              precision    recall  f1-score   support

           0       0.86      0.87      0.87      1298
           1       0.86      0.85      0.85      1202

    accuracy                           0.86      2500
   macro avg       0.86      0.86      0.86      2500
weighted avg       0.86      0.86      0.86      2500

In [24]:
# Таблица с результатами

res2 = {'Type':'TfidfVectorizer', 'Score':acc_score}

results = results.append(res2, ignore_index=True)

In [25]:
results

    Score             Type
0  0.8612  CountVectorizer
1  0.8604  TfidfVectorizer

При изменении различных параметров векторайзеров самое высокое значение скора получилось при отключении опций max_features и stop_words, но в целом значительной разницы в результататах между CountVectorizer и TfidfVectorizer нет.

По PCA - не обнаружила информации в лекции, буду признательна, если подскажете, где про это можно прочитать.